name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: handle env var
        run: |
          curl -LO https://raw.githubusercontent.com/clearfraction/tools/master/build.sh
          chmod +x build.sh
          docker run --privileged --cap-add=SYS_ADMIN --security-opt apparmor:unconfined -e GITLAB_API_KEY="$GITLAB_API_KEY" -v $(pwd):/home clearlinux:latest sh -c "cd /home && ./build.sh"
        env:
          GITLAB_API_KEY: ${{ secrets.GITLAB_API_KEY }}
        
